version: '3.8'

services:

  redis:
    image: redis:alpine
    container_name: hospital-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: hospital-zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: hospital-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    restart: unless-stopped
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: hospital-kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    restart: unless-stopped

volumes:
  redis-data:
  zookeeper-data:
  zookeeper-logs:
  kafka-data: